### ISSUE TITLE
Buttons not working

### ISSUE THREAD

**Issue by grubux** [stevenpersia/tinder-expo#1]
Hi, none of the buttons are working except the tab bar. I tried on multiple platforms : android studio, my phone, my phone with the QRCode of the expo website (preview), webview in expo and the web android simulator on expo preview  website. Still got the same issue.

**Comment by stevenpersia** [comment]
Hi @grubux !
Thank you for your issue. But I think there is a misunderstood, it's an UI clone so there is no logic on this repo. :+1:
