### ISSUE TITLE
No LICENSE file

### ISSUE THREAD

**Issue by acuozzo** [stevenpersia/tinder-expo#3]
Is this MIT licensed like tinder-react-native? Thanks!

**Comment by stevenpersia** [comment]
Yo @acuozzo !

You are right. That why I've just created a LICENCE file. I confirm you this is a MIT project.

**Comment by acuozzo** [comment]
Excellent. Thank you very much!

**Comment by acuozzo** [comment]
Excellent. Thank you very much!
