### ISSUE TITLE
Can we get this working for the latest version of Expo?

### ISSUE THREAD

**Issue by neelsomani** [stevenpersia/tinder-expo#7]
Think this version is pretty old so it doesn't run on my phone :( thanks

**Comment by qhello** [comment]
Hi @neelsomani,

Just opened a PR regarding this.

**Comment by LianBond** [comment]
https://github.com/LianBond/tinder-expo-45.0.0

**Comment by stevenpersia** [comment]
Thank you for your contributions guys :heart: You can pull latest modifications.

**Comment by btray77** [comment]
Also, might want to update the expo go client.  Thanks
